### PR TITLE
Add final CSS touches

### PR DESCRIPTION
**Pull request by yash244466666**
Added the final CSS touches.

Modify/Add the following files:

-[dist](https://github.com/yash244466666/Leaderboard-M2W4/tree/setup-project/dist)/
--[bundle.js](https://github.com/yash244466666/Leaderboard-M2W4/blob/setup-project/dist/bundle.js)
--[index.html](https://github.com/yash244466666/Leaderboard-M2W4/blob/setup-project/dist/index.html)
-[src](https://github.com/yash244466666/Leaderboard-M2W4/tree/setup-project/src)/
--[index.html](https://github.com/yash244466666/Leaderboard-M2W4/blob/setup-project/src/index.html)
--[style.css](https://github.com/yash244466666/Leaderboard-M2W4/blob/setup-project/src/style.css)

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @yash244466666, please add the future features section to your readme

**Comment by yash244466666** [comment]
@prolajumokeoni, you got it; thank you. 😁

**Review by prolajumokeoni — APPROVED** [review]
Hi @yash244466666 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 
- Good design 💯 
- Good Readme 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by yash244466666** [comment]
@prolajumokeoni Add Future Features section to readme as you instructed

**Comment by yash244466666** [comment]
@prolajumokeoni thank you so much

**Pull request merged**
